# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: test

container:
  image: nvtienanh/cmake:5.0
  volumes:
    - /temp-cache:/temp-cache
    - /nfsdata:/nfsdata
    - /blobfuse2:/blobfuse2

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    df -h
    whoami
    ls -la /temp-cache
    ls -la /nfsdata
    ls -la /blobfuse2
    which ccache
    echo 'Hello' > /temp-cache/hello.txt
    echo 'Hello nfsdata' > /nfsdata/hello.txt
    echo 'Hello blobfuse2' > /blobfuse2/hello.txt
    echo Add other tasks to build, test, and deploy your project.
    echo $(Agent.HomeDirectory)
    echo $(Agent.BuildDirectory)
  displayName: 'Run a multi-line script'
