# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: test

container:
  image: nvtienanh/cmake:5.0
  volumes:
    - /temcache:/blobfuse2
    # - /blobfuse2:/blobfuse2
variables:
  CCACHE_DIR: /blobfuse2
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    df -h
    whoami
    echo $UID
    echo $GID
    ls -la /temcache
    ls -la /blobfuse2
    which ccache
    echo 'Hello' > /temcache/hello.txt

    echo Add other tasks to build, test, and deploy your project.
    echo $(Agent.HomeDirectory)
    echo $(Agent.BuildDirectory)
    echo $(System.DefaultWorkingDirectory)
  displayName: 'Run a multi-line script'

- task: Cache@2
  displayName: Ccache caching
  inputs:
    key: 'ccache | "$(Agent.OS)" | $(Build.SourceVersion)'
    path: $(CCACHE_DIR)
    restoreKeys: | 
      ccache | "$(Agent.OS)"

- script: |
    cmake -B build -G Ninja
    cmake --build ./build
  displayName: 'Run cmake'