# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
    name: test
jobs:
- job: no_checkout
  
  container:
    image: nvtienanh/cmake:5.0
    volumes:
      - /sofacache:/sofacache
      - /conan:/conan
  variables:
    CCACHE_DIR: /sofacache
    CONAN_USER_HOME: /conan
  steps:
  - task: Cache@2
    displayName: Ccache caching
    inputs:
      key: 'ccache | "$(Agent.OS)" | $(Build.SourceVersion)'
      path: $(CCACHE_DIR)
      restoreKeys: | 
        ccache | "$(Agent.OS)"
      cacheHitVar: CACHE_RESTORED

  - script: |
      conan profile detect
      conan install . --output-folder=build --build=missing
      cmake -B build -G Ninja
      cmake --build ./build
    displayName: 'Run cmake'



# - job: checkout
#   dependsOn: no_checkout

#   container:
#     image: nvtienanh/cmake:5.0
#     volumes:
#       - /temcache:/temcache
#       - /blobfuse2:/blobfuse2
#   steps:
#   - checkout: none
#   - script: |
#       ls -la /temcache
#       azcopy --version
#   condition: always()
#   displayName: 'Run cmake'


